# Generated by Django 4.2.2 on 2025-06-12 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailing_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите тему письма",
                        max_length=150,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Введите содержимое письма",
                        null=True,
                        verbose_name="Содержимое письма",
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ["title"],
            },
        ),
        migrations.RenameModel(
            old_name="Addressee",
            new_name="Client",
        ),
        migrations.CreateModel(
            name="Mailings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации продукта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Дата последнего изменения информации о продукте",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Завершена"),
                            ("created", "Создана"),
                            ("launched", "Запущена"),
                        ],
                        default="created",
                        max_length=10,
                    ),
                ),
                (
                    "client",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Укажите получателя рассылки",
                        null=True,
                        to="mailing_service.client",
                        verbose_name="Получатель рассылки",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите сообщение",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mailing_service.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите автора рассылки",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ["created_at", "updated_at", "status", "owner", "message"],
            },
        ),
    ]
