# Generated by Django 4.2.2 on 2025-06-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0002_message_rename_addressee_client_mailings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailings",
            name="client",
            field=models.ManyToManyField(
                blank=True,
                help_text="Укажите получателя рассылки",
                to="mailing_service.client",
                verbose_name="Получатель рассылки",
            ),
        ),
    ]
