# Generated by Django 4.2.2 on 2025-06-12 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailing_service", "0003_alter_mailings_client"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mailings",
            new_name="Mailing",
        ),
    ]
