# Generated by Django 4.2.2 on 2025-06-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0005_alter_client_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Укажите клиентов рассылки",
                to="mailing_service.client",
                verbose_name="Клиенты",
            ),
        ),
    ]
