# Generated by Django 4.2.2 on 2025-06-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0006_alter_mailing_clients"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="clients",
            new_name="client",
        ),
    ]
