# Generated by Django 4.2.2 on 2025-06-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0007_rename_clients_mailing_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="client",
            new_name="clients",
        ),
    ]
