# Generated by Django 4.2.2 on 2025-06-13 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0008_rename_client_mailing_clients"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttemptMailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации продукта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("successfully", "Успешно"),
                            ("unsuccessfully", "Не успешно"),
                        ],
                        default="successfully",
                        max_length=15,
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ответ почтового сервера"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        help_text="Укажите рассылку",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing_service.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
        ),
    ]
