# Generated by Django 4.2.2 on 2025-06-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0010_alter_attemptmailing_options_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Завершена"),
                    ("created", "Создана"),
                    ("launched", "Запущена"),
                ],
                default="created",
                max_length=10,
            ),
        ),
    ]
