# Generated by Django 4.2.2 on 2025-06-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0011_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["created_at", "finished_at", "status", "owner", "message"],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="mailing",
            name="finished_at",
            field=models.DateTimeField(
                null=True, verbose_name="Дата окончания рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания рассылки"
            ),
        ),
    ]
