# Generated by Django 4.2.2 on 2025-06-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing_service",
            "0012_alter_mailing_options_remove_mailing_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptmailing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время попытки рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время создания рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="finished_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время окончания рассылки"
            ),
        ),
    ]
