# Generated by Django 4.2.2 on 2025-06-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing_service",
            "0015_alter_attemptmailing_options_alter_client_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="manager",
            new_name="owner",
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.CharField(max_length=20, unique=True, verbose_name="Email"),
        ),
    ]
