# Generated by Django 4.2.2 on 2025-06-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0017_alter_client_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=50, unique=True, verbose_name="Email"),
        ),
    ]
